name: Build docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: 'Snake-Whisper/docker-borgbackup'
          ref: 'borgbackup'
      - name: List dir
        run: ls -alh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: false
          tags: snakewhisper/docker-borgbackup:test
          platforms: linux/amd64,linux/arm64
          context: .
